name: Deploy SQL Database

on:
  push:
    branches:
      - main

jobs:
  setup-database:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SQL Server Command Line Tools (sqlcmd)
        run: |
          # Install Microsoft ODBC Driver 17 for SQL Server
          Invoke-WebRequest -Uri https://aka.ms/downloadmsodbcsql -OutFile msodbc.msi
          Start-Process msiexec.exe -ArgumentList "/i", "msodbc.msi", "/quiet", "/norestart" -NoNewWindow -Wait
          Remove-Item msodbc.msi -Force

          # Install SQLCMD tools
          Invoke-WebRequest -Uri https://aka.ms/sqlcmdline -OutFile sqlcmd.msi
          Start-Process msiexec.exe -ArgumentList "/i", "sqlcmd.msi", "/quiet", "/norestart" -NoNewWindow -Wait
          Remove-Item sqlcmd.msi -Force

      - name: Test Connection to SQL Server
        env:
          SERVER: ${{ secrets.SERVER }}  # Use comma instead of colon for port
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          # Running sqlcmd to test connection
          sqlcmd -S $env:SERVER -U $env:DB_USER -P $env:DB_PASSWORD -Q "SELECT @@VERSION"
