name: Deploy SQL Database

on:
  push:
    branches:
      - main

jobs:
  setup-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SQL Server client
        run: |
          sudo apt-get update
          sudo apt-get install -y curl apt-transport-https
          curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc > /dev/null
          echo "deb [arch=amd64] https://packages.microsoft.com/ubuntu/22.04/prod jammy main" | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev



      - name: Add SQL Server tools to PATH
        run: echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc && source ~/.bashrc

      - name: Test Connection to SQL Server
        env:
          SERVER: ${{ secrets.SERVER }}  # Use comma instead of colon for port
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          sqlcmd -S $SERVER -U $DB_USER -P $DB_PASSWORD -Q "SELECT @@VERSION"
