name: Deploy SQL Database

on:
  push:
    branches:
      - main

jobs:
  setup-database:
    runs-on: windows-latest
    timeout-minutes: 10  # Increase overall timeout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SQL Tools
        shell: powershell
        run: |
          # Install using Chocolatey (more reliable)
          choco install sqlserver-cmdlineutils -y --no-progress

      - name: Test SQL Connection with Timeout
        shell: powershell
        env:
          SERVER: ${{ secrets.SERVER }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          $retryCount = 0
          $maxRetries = 3
          $connectionTimeout = 30  # Seconds

          while ($retryCount -lt $maxRetries) {
              try {
                  Write-Host "Attempt $($retryCount + 1) of $maxRetries - Waiting $connectionTimeout seconds for connection..."
                  
                  # Set connection timeout parameter
                  $result = sqlcmd -S "$env:SERVER" -U "$env:DB_USER" -P "$env:DB_PASSWORD" `
                                  -l $connectionTimeout `
                                  -Q "SELECT 'Connection successful at ' + FORMAT(GETDATE(), 'HH:mm:ss') AS Result"
                  
                  if ($LASTEXITCODE -eq 0) {
                      Write-Host $result
                      Write-Host "Connection established successfully!"
                      exit 0
                  }
                  else {
                      throw "Connection failed with exit code $LASTEXITCODE"
                  }
              }
              catch {
                  Write-Host "::warning::Attempt failed: $_"
                  $retryCount++
                  if ($retryCount -lt $maxRetries) {
                      Start-Sleep -Seconds 10  # Wait before retrying
                  }
              }
          }

          Write-Host "::error::Failed to connect after $maxRetries attempts"
          exit 1
